// D&D5e 활동(activity) 이름 영문→한국어 사전 (자동 생성, 734종)
// activities[<id>].name 을 영문 정확 일치 시 한국어로 치환.
export const ACTIVITY_NAME_MAP = {
  "(free casting)": "(무료 시전)",
  "10: Casts Wish": "10: 소원 시전",
  "1: Attacks You": "1: 당신을 공격",
  "1st Save": "1번째 내성",
  "1st and 2nd Command": "1번째 및 2번째 명령",
  "2nd Save": "2번째 내성",
  "2—9: Obeys Commands": "2—9: 명령에 복종",
  "3rd Command": "3번째 명령",
  "Absorb Spell": "주문 흡수",
  "Acid": "산성",
  "Action": "행동",
  "Activate": "발동",
  "Activate (3 by 5 ft.)": "발동 (3×5피트)",
  "Activate (4 by 6 ft.)": "발동 (4×6피트)",
  "Activate (5 by 7 ft.)": "발동 (5×7피트)",
  "Activate (6 by 9 ft.)": "발동 (6×9피트)",
  "Activate Broom": "빗자루 발동",
  "Activate Sword: Dexterity": "검 발동: 민첩",
  "Activate Sword: Stength": "검 발동: 근력",
  "Adamantine Armor": "아다만틴 갑옷",
  "Add Design": "도안 추가",
  "Add Trapped Creature": "갇힌 크리처 추가",
  "Add'l Poison Damage": "추가 독성 피해",
  "Addle": "혼미",
  "Adrenaline Rush: Dash": "아드레날린 분출: 질주",
  "Affect New Area": "새 범위에 영향",
  "Alter Terrain": "지형 변경",
  "Ammunition of Slaying": "학살의 탄약",
  "Ammunition, +1, +2, or +3": "탄약, +1, +2, 또는 +3",
  "Animal Friendship": "동물 친밀화",
  "Animate": "생기 부여",
  "Animate Corpses": "시체 활성화",
  "Antipathy Save": "반공감 내성",
  "Apply Glue": "접착제 바르기",
  "Apply Lethargy": "무기력 부여",
  "Apply Makeup": "화장하기",
  "Apply Oil": "기름 바르기",
  "Apply Oil to Ammunition": "탄약에 기름 바르기",
  "Apply Oil to Weapon": "무기에 기름 바르기",
  "Aquatic Adaptation": "수중 적응",
  "Armor of Resistance": "저항의 갑옷",
  "Armor of Vulnerability": "취약의 갑옷",
  "Armor, +1, +2, or +3": "갑옷, +1, +2, 또는 +3",
  "Arrow of Restraint": "포박의 화살",
  "Arrow of Transport": "전송의 화살",
  "Assemble a Tiny Item": "초소형 물건 조립",
  "Attach Horseshoes": "편자 부착",
  "Attached: Damage": "부착됨: 피해",
  "Attack": "공격",
  "Attack Construct": "구조물 공격",
  "Attack Deflection": "공격 빗나가기",
  "Attack Sworn Enemy": "맹세한 적 공격",
  "Attack at Advantage": "유리하게 공격",
  "Attack vs Giant": "거인 상대 공격",
  "Attack with Advantage": "유리하게 공격",
  "Attack: Claws": "공격: 발톱",
  "Attack: Fangs/Horns": "공격: 송곳니/뿔",
  "Attack: Hooves": "공격: 발굽",
  "Attacked if Grappling": "붙잡고 있을 때 공격받음",
  "Attempt Escape": "탈출 시도",
  "Attempt to Move": "이동 시도",
  "Attempt to Trap Creature": "크리처 포획 시도",
  "Attunement Save": "조율 내성",
  "Aura of Courage": "용기의 오라",
  "Aura of Protection": "보호의 오라",
  "Awaken": "각성",
  "Banish to Maze": "미로로 추방",
  "Barkskin": "나무껍질 피부",
  "Beckon Element": "원소 소환",
  "Become Werebear": "웨어베어로 변신",
  "Become Wereboar": "웨어보어로 변신",
  "Become Wererat": "웨어랫으로 변신",
  "Become Weretiger": "웨어타이거로 변신",
  "Become Werewolf": "웨어울프로 변신",
  "Berserk Check": "광폭화 판정",
  "Berserker Axe": "광전사의 도끼",
  "Beseech Entity": "존재에게 간청",
  "Bestow Foresight": "미래시 부여",
  "Bind": "결박",
  "Blade Ring": "칼날 고리",
  "Blade Wall": "칼날 벽",
  "Blinding Save": "실명 내성",
  "Bloodied Attack": "피투성이 공격",
  "Blow Horn": "뿔피리 불기",
  "Blue Sapphire": "블루 사파이어",
  "Bonus Attack Damage": "추가 공격 피해",
  "Bonus Hex Damage": "추가 주박 피해",
  "Bonus Mark Damage": "추가 표식 피해",
  "Break Check": "파괴 판정",
  "Break Enchantment": "마법 해제",
  "Break Item": "물건 파괴",
  "Breath Weapon (Cone)": "브레스 무기(원뿔)",
  "Breath Weapon (Line)": "브레스 무기(직선)",
  "Brutal Strike": "잔혹한 일격",
  "Bullseye Lantern": "망원 랜턴",
  "Burn": "연소",
  "Burn and Cast": "연소 후 시전",
  "Burst Chain Check": "사슬 끊기 판정",
  "Burst Check": "끊기 판정",
  "Burst Rope": "밧줄 끊기",
  "Burst of Colorful Light (78-82)": "다채로운 빛의 폭발 (78-82)",
  "Button 1 Attack": "버튼 1 공격",
  "Button 2 Attack": "버튼 2 공격",
  "Button 2 Versatile Attack": "버튼 2 다재다능 공격",
  "Button 3 Attack": "버튼 3 공격",
  "Call Dragons": "드래곤 부르기",
  "Call Swarm of Rats": "쥐 무리 부르기",
  "Calm Check": "진정 판정",
  "Card Effect": "카드 효과",
  "Card Effect: Advantage": "카드 효과: 유리",
  "Card Effect: Draw Two": "카드 효과: 두 장 뽑기",
  "Card Effect: Gems": "카드 효과: 보석",
  "Card Effect: Jewelry": "카드 효과: 보석류",
  "Card Effect: Resolve": "카드 효과: 결의",
  "Card Effect: Start": "카드 효과: 시작",
  "Card Effect: Wish": "카드 효과: 소원",
  "Careful Spell": "신중한 주문",
  "Carve Pattern": "문양 새기기",
  "Cast": "시전",
  "Cast (free casting)": "시전 (무료 시전)",
  "Cast Spell": "주문 시전",
  "Cast Wish": "소원 시전",
  "Cast and Attack": "시전 후 공격",
  "Cast and Control": "시전 후 제어",
  "Cast and Fire": "시전 후 발사",
  "Cast and Heat": "시전 후 가열",
  "Cast and Hold": "시전 후 유지",
  "Cast on Window or Door": "창문 또는 문에 시전",
  "Cast over Area": "범위에 시전",
  "Catch Cheating": "속임수 적발",
  "Change Appearance": "외형 변경",
  "Change Conditions": "상태 변경",
  "Change Form": "형태 변경",
  "Channel Divinity: Turn Undead": "신성 발현: 언데드 퇴치",
  "Charge Damage": "돌격 피해",
  "Check Deck Size": "덱 크기 확인",
  "Check: Stanch Wound": "판정: 지혈",
  "Chill": "한기",
  "Chisel a Symbol or Hole": "문양 또는 구멍 새기기",
  "Clap of Thunder": "천둥의 박수",
  "Click Heels": "뒤꿈치 맞부딪치기",
  "Cloud of Oversized Butterflies (41-45)": "거대한 나비 구름 (41-45)",
  "Cloud's Jaunt": "구름의 도약",
  "Coat Blade with Poison": "칼날에 독 바르기",
  "Cold": "냉기",
  "Cold Damage": "냉기 피해",
  "Collapsing Structure Save": "붕괴 구조물 내성",
  "Colossus Slayer": "거인 학살자",
  "Command": "명령",
  "Command Obedience": "복종 명령",
  "Command: Move and Attack": "명령: 이동 후 공격",
  "Compel to Die": "죽음 강요",
  "Conjure": "소환",
  "Conjure Feast": "연회 소환",
  "Conjure Pillar": "기둥 소환",
  "Consume": "소비",
  "Consume Damage Pool": "피해 풀 소비",
  "Consume Feast": "연회 소비",
  "Consume Focus Point": "집중 점수 소비",
  "Consume Oil": "기름 소비",
  "Control the Sphere": "구체 제어",
  "Count Beans": "콩 세기",
  "Count Number of Cards": "카드 수 세기",
  "Cover Creature": "크리처 덮기",
  "Create Aura": "오라 생성",
  "Create Bead": "구슬 생성",
  "Create Berries": "열매 생성",
  "Create Cage": "우리 생성",
  "Create Circle": "원 생성",
  "Create Clay Golem": "점토 골렘 생성",
  "Create Cloud": "구름 생성",
  "Create Contingency": "조건화 생성",
  "Create Door": "문 생성",
  "Create Flesh Golem": "살점 골렘 생성",
  "Create Globe": "구체 생성",
  "Create Illusion": "환영 생성",
  "Create Iron Golem": "강철 골렘 생성",
  "Create Lightning Spheres": "번개 구체 생성",
  "Create Lights": "빛 생성",
  "Create New Sunbeam": "새 햇살 생성",
  "Create Panels": "패널 생성",
  "Create Ring": "고리 생성",
  "Create Segmented Wall": "분할된 벽 생성",
  "Create Sensor": "감지기 생성",
  "Create Simulacrum": "시뮬라크럼 생성",
  "Create Single Wall": "단일 벽 생성",
  "Create Solid Box": "단단한 상자 생성",
  "Create Spectral Sword": "유령 검 생성",
  "Create Stone Golem": "바위 골렘 생성",
  "Create Storm": "폭풍 생성",
  "Create Tsunami": "해일 생성",
  "Create Wall": "벽 생성",
  "Create Ward": "방비 생성",
  "Create Whirlpool": "소용돌이 생성",
  "Crush": "분쇄",
  "Cunning Sneak Attack": "교활한 기습 공격",
  "Curse Ability": "능력 저주",
  "Curse Actions": "행동 저주",
  "Curse Attacks": "공격 저주",
  "Curse New Creature": "새 크리처 저주",
  "Curse Resilience": "저주 저항",
  "Cut with Words": "말로 베기",
  "Dagger": "단검",
  "Damage": "피해",
  "Damage & Save": "피해 및 내성",
  "Damage Forbidden Creature": "금지된 크리처 피해",
  "Damage Rope": "밧줄 손상",
  "Damage While Poisoned": "중독 중 피해",
  "Damage: Grappled": "피해: 붙잡힘",
  "Damage: Infernal Wound": "피해: 지옥의 상처",
  "Damage: Outside Water": "피해: 물 밖",
  "Damage: Running Water": "피해: 흐르는 물",
  "Damage: Start of Turn": "피해: 턴 시작",
  "Damage: Sunlight": "피해: 햇빛",
  "Damage: Swallowed": "피해: 삼켜짐",
  "Dancing Sword": "춤추는 검",
  "Dash": "질주",
  "Daylight Save": "햇빛 내성",
  "Days to Reform": "재구성 일수",
  "Days: New Body": "일수: 새 육체",
  "Daze": "혼절",
  "Death": "죽음",
  "Decrease Exhaustion": "탈진 감소",
  "Defender": "수호자",
  "Demon Armor": "데몬의 갑옷",
  "Designate Sanctuary": "성소 지정",
  "Detach Attempt": "떼어내기 시도",
  "Detect Hostile Creature": "적대적 크리처 탐지",
  "Detect Poisoned Drink": "독이 든 음료 탐지",
  "Detect Poisoned Object": "독이 묻은 물체 탐지",
  "Detect Secret Door/Trap": "비밀문/함정 탐지",
  "Detect Spoiled or Poisoned Food": "상하거나 독이 든 음식 탐지",
  "Determine Number of Beads": "구슬 수 결정",
  "Determine Number of Pinches": "한 줌 수 결정",
  "Determine Number of Pots": "단지 수 결정",
  "Determine Ounces": "온스 결정",
  "Determine Position by Stargazing": "별 관측으로 위치 결정",
  "Diamond Light": "다이아몬드 빛",
  "Discern Previous Contents": "이전 내용물 파악",
  "Discern Value": "가치 파악",
  "Discord": "불협화음",
  "Disengage": "이탈",
  "Dismissal": "해제",
  "Display Dazzling Hues": "현란한 색조 표출",
  "Distant Spell": "원거리 주문",
  "Divine Sense": "신성 감각",
  "Divine Spark: Heal": "신성한 불꽃: 치유",
  "Divine Spark: Save": "신성한 불꽃: 내성",
  "Dominate Beast": "야수 지배",
  "Douse Space": "공간 소등",
  "Draconic Flight": "용족 비행",
  "Draft a Map": "지도 작성",
  "Dragon Slayer": "용살자",
  "Dragon Wings": "용 날개",
  "Drain Life": "생명력 흡수",
  "Draw Card": "카드 뽑기",
  "Draw Cards": "카드 뽑기",
  "Drink": "마시기",
  "Drink Potion": "물약 마시기",
  "Dump Beans": "콩 쏟기",
  "Duplicate Wax Seal": "밀랍 봉인 복제",
  "Dwarven Plate": "드워프 판금 갑옷",
  "Earthquake: Concentration Save": "지진: 집중 내성",
  "Earthquake: Fissure": "지진: 균열",
  "Earthquake: Object Damage": "지진: 물체 피해",
  "Earthquake: Save": "지진: 내성",
  "Efreeti Chain": "이프리트의 사슬",
  "Eldritch Master": "섬뜩한 대가",
  "Elemental Compulsion": "원소 충동",
  "Elven Chain": "엘프 사슬 갑옷",
  "Emanation Save": "발산 내성",
  "Emerald": "에메랄드",
  "Empowered Spell": "강화된 주문",
  "Empowered Strike": "강화된 일격",
  "Enchant Weapon": "무기 마법 부여",
  "End Vibrations": "진동 종료",
  "End of Turn Damage": "턴 종료 피해",
  "End of Turn Fissures": "턴 종료 균열",
  "End of Turn Save": "턴 종료 내성",
  "Energy Bow": "에너지 활",
  "Energy Ladder": "에너지 사다리",
  "Engulf in Flames": "화염에 휩싸기",
  "Engulfed": "휩싸임",
  "Engulfed: Damage": "휩싸임: 피해",
  "Enlarge": "확대",
  "Enrichment": "정화",
  "Entangle": "휘감기",
  "Enter Border Ethereal": "경계 에테르계 진입",
  "Enter/Exit Astral Plane": "영체계 진입/이탈",
  "Erase Name": "이름 지우기",
  "Escape": "탈출",
  "Escape Check": "탈출 판정",
  "Escape Check (1-4)": "탈출 판정 (1-4)",
  "Escape Check (11-16)": "탈출 판정 (11-16)",
  "Escape Check (17-20)": "탈출 판정 (17-20)",
  "Escape Check (5-10)": "탈출 판정 (5-10)",
  "Escape Corpse": "시체에서 탈출",
  "Escape from Corpse": "시체에서 탈출",
  "Etherealness": "에테르화",
  "Evoke Blade": "칼날 불러내기",
  "Exhale": "내뿜기",
  "Expand Use": "사용 확장",
  "Expend First Spell": "첫 번째 주문 소모",
  "Expend Rage": "분노 소모",
  "Expend Second Spell": "두 번째 주문 소모",
  "Expend Second Wind": "재충전 소모",
  "Expend Use": "사용 소비",
  "Expend d10 Hit Dice": "d10 히트 다이스 소모",
  "Expend d12 Hit Dice": "d12 히트 다이스 소모",
  "Expend d6 Hit Dice": "d6 히트 다이스 소모",
  "Expend d8 Hit Dice": "d8 히트 다이스 소모",
  "Explosion Damage": "폭발 피해",
  "Explosive Emanation": "폭발성 발산",
  "Explosive Rune": "폭발성 룬",
  "Extended Spell": "연장된 주문",
  "Extensive and Body Part": "광범위 및 신체 부위",
  "Extensive and Garment": "광범위 및 의복",
  "Extensive and Picture": "광범위 및 사진",
  "False Life": "거짓 목숨",
  "Fear": "공포",
  "Fear (Affects Beasts Only)": "공포 (야수에게만 영향)",
  "Fiend and Undead Damage": "마족 및 언데드 피해",
  "Fiend/Undead Save": "마족/언데드 내성",
  "Find Familiar": "패밀리어 찾기",
  "Find Familiar (Expanded Options)": "패밀리어 찾기 (확장 옵션)",
  "Find Familiar with Flight": "비행 가능 패밀리어 찾기",
  "Find Familiar with Swimming": "수영 가능 패밀리어 찾기",
  "Fire": "화염",
  "Fire Opal Flames": "파이어 오팔 화염",
  "Fireball (Lvl. 5)": "화염구 (5레벨)",
  "First Command Word": "첫 번째 명령어",
  "First Roar: Save": "첫 번째 포효: 내성",
  "First Save": "첫 번째 내성",
  "First Use": "첫 번째 사용",
  "Firsthand and Body Part": "직접 및 신체 부위",
  "Firsthand and Garment": "직접 및 의복",
  "Firsthand and Picture": "직접 및 사진",
  "Flame Tongue": "플레임 텅",
  "Flood, Part, or Redirect": "범람, 가르기, 또는 방향 전환",
  "Flurry of Blows": "연격",
  "Fly": "비행",
  "Forceful Bash": "강력한 강타",
  "Forge Pact Weapon": "조약 무기 제작",
  "Forge Telepathic Link": "정신감응 연결 구축",
  "Fountain": "분수",
  "Free Cast Roll": "무료 시전 굴림",
  "Free Trapped Creature": "갇힌 크리처 해방",
  "Freeze Water": "물 얼리기",
  "Frigid Air": "차가운 공기",
  "Frost Brand": "프로스트 브랜드",
  "Gain Truesight": "진시야 획득",
  "Gain X-Ray Vision": "투시 시야 획득",
  "Gaze of Two Minds": "두 마음의 응시",
  "Geyser": "간헐천",
  "Giant Slayer": "거인 살해자",
  "Giants' Bane (On Crit)": "거인의 천적 (치명타 시)",
  "Gift Water Breathing": "수중 호흡 부여",
  "Goat of Terror": "공포의 염소",
  "Goat of Travail": "고난의 염소",
  "Goat of Traveling": "여행의 염소",
  "Grant Truesight": "진시야 부여",
  "Grapple": "붙잡기",
  "Grapple Escape Check": "붙잡기 탈출 판정",
  "Grapple/Shove": "붙잡기/밀치기",
  "Grappled: Damage": "붙잡힘: 피해",
  "Grass Cover (61-64)": "풀 엄폐 (61-64)",
  "Grip Edges": "가장자리 붙잡기",
  "Grow Tower": "탑 성장",
  "Gust of Wind": "돌풍",
  "HP Max Decr.": "최대 HP 감소",
  "HP Max Decrease": "최대 HP 감소",
  "Hammer of Thunderbolts": "천둥벼락의 망치",
  "Heal (Largest Hit Die)": "치유 (가장 큰 히트 다이스)",
  "Heal (Smallest Hit Die)": "치유 (가장 작은 히트 다이스)",
  "Heal Fully": "완전 치유",
  "Healing Light": "치유의 빛",
  "Heavy Rain (36-40)": "폭우 (36-40)",
  "Heightened Spell": "고양된 주문",
  "Hide": "은신",
  "Hide Chest": "상자 숨기기",
  "Hill's Tumble": "언덕의 굴림",
  "Holy Avenger": "홀리 어벤저",
  "Holy Nimbus": "신성한 후광",
  "Hurl Fire": "화염 던지기",
  "Hurl Hammer": "망치 던지기",
  "Hurl Through Hell": "지옥으로 내던지기",
  "Identify Alcohol": "술 식별",
  "Identify Plant": "식물 식별",
  "Imbue Weapon": "무기 주입",
  "Improve Fate": "운명 개선",
  "Improve Flavor": "풍미 개선",
  "Improved Hunter's Mark Damage": "향상된 사냥꾼의 표식 피해",
  "Improvise a Song": "즉흥 노래",
  "Increase Range": "사거리 증가",
  "Incubus": "인큐버스",
  "Indigo Save (Con)": "남색 내성 (건강)",
  "Initial Cast": "최초 시전",
  "Initial Save": "최초 내성",
  "Innate Sorcery": "타고난 마법",
  "Inscribe Glyph": "결계 문양 새기기",
  "Inscribe Mark": "표식 새기기",
  "Insect Cloud": "곤충 구름",
  "Inspire": "고무",
  "Instill Vibrations": "진동 주입",
  "Intelligence Saving Throw": "지능 내성 굴림",
  "Intercept Attack": "공격 차단",
  "Interpose": "끼어들기",
  "Invest with Resistance": "저항 부여",
  "Knock Out": "기절시키기",
  "Large Horizontal Portal": "대형 수평 차원문",
  "Large Vertical Portal": "대형 수직 차원문",
  "Life Stealing": "생명 강탈",
  "Light": "점화",
  "Light Candle (Minutes)": "양초 점화 (분)",
  "Light Save": "광휘 내성",
  "Lightning": "번개",
  "Lightning Bolt": "번개 줄기",
  "Lightning Bolt (Lvl. 5)": "번개 줄기 (5레벨)",
  "Lightning Sphere Save": "번개 구체 내성",
  "Lightning Strike": "번개 강타",
  "Lingering Acid Damage": "지속 산성 피해",
  "Locate Animals or Plants": "동식물 추적",
  "Long Panels": "긴 패널",
  "Luck": "행운",
  "Luck Blade": "행운의 검",
  "Mage Armor": "마법사의 갑옷",
  "Make Immovable": "고정 상태로 만들기",
  "Make Repelling": "반발 상태로 만들기",
  "Make Signature": "서명하기",
  "Mark Creature": "크리처 표식",
  "Master Light Martial Weapon": "경량 군용 무기 통달",
  "Master Simple Weapon": "단순 무기 통달",
  "Master Spell": "주문 통달",
  "Max HP Decrease": "최대 HP 감소",
  "Mend or Sew": "수선 또는 바느질",
  "Mentally Command": "정신으로 명령",
  "Merge with the Shadows": "그림자와 융합",
  "Metal Shell": "금속 껍질",
  "Mimic Handwriting": "필체 모방",
  "Mirror": "거울",
  "Mithral Armor": "미스랄 갑옷",
  "Modify Footwear": "신발 개조",
  "Move": "이동",
  "Move Hound": "사냥개 이동",
  "Move Levers": "레버 조작",
  "Move Lights": "빛 이동",
  "Move Mark": "표식 이동",
  "Move and Save": "이동 후 내성",
  "Moving Attack": "이동 공격",
  "Multiattack Defense": "다중공격 방어",
  "Natural Weapons": "자연 무기",
  "Nature Magician": "자연 마법사",
  "Necrotic Divine Strike": "사령 신성 강타",
  "Negative Energy Save": "음에너지 내성",
  "Nine Lives Stealer": "아홉 생명 강탈자",
  "Non-Fiend or Undead Damage": "비마족 또는 언데드 피해",
  "Oathbow": "맹세의 활",
  "Object Damage": "물체 피해",
  "Obscure": "가리기",
  "Obscure Area": "범위 가리기",
  "On Damage Save": "피해 시 내성",
  "Open Bottle": "병 열기",
  "Open Fortress Door": "요새 문 열기",
  "Open Wings": "날개 펼치기",
  "Overgrowth": "과잉 성장",
  "Pain": "고통",
  "Paint": "칠하기",
  "Paint a Recognizable Image": "알아볼 수 있는 그림 그리기",
  "Panels": "패널",
  "Paralyze": "마비시키기",
  "Paralyzed": "마비",
  "Pass without Trace": "신출귀몰",
  "Patient Defense": "인내의 방어",
  "Patient Defense (Focus Point)": "인내의 방어 (집중 점수)",
  "Per Turn Save": "턴당 내성",
  "Phantasm Damage": "환영 피해",
  "Pick a Lock/Disarm a Trap": "자물쇠 따기/함정 해제",
  "Place Curse": "저주 걸기",
  "Place Emanation": "발산 배치",
  "Place Shackles": "족쇄 채우기",
  "Plant Bean": "콩 심기",
  "Plant Rod": "막대 심기",
  "Plate Armor of Etherealness": "에테르화 판금 갑옷",
  "Play Pipes": "피리 연주",
  "Play a Known Tune": "아는 곡 연주",
  "Play to Win": "이기기 위한 플레이",
  "Plot a Course": "경로 설정",
  "Poison": "독성",
  "Poison Save": "독성 내성",
  "Pole": "장대",
  "Possess Humanoid": "인간형 빙의",
  "Potent Spellcasting: Heal": "강력한 주문시전: 치유",
  "Pour on Ground": "바닥에 붓기",
  "Preserve": "보존",
  "Primal Strike": "원시의 일격",
  "Probe Deeper": "더 깊이 탐색",
  "Protect": "보호",
  "Protective Field": "보호장",
  "Pry Open": "비집어 열기",
  "Pull Check": "당기기 판정",
  "Pull and Throw": "당겨서 던지기",
  "Puller Damage": "당기는 자 피해",
  "Pure Rebuke": "순수한 질책",
  "Push": "밀어내기",
  "Quickened Spell": "신속한 주문",
  "Radiant Divine Strike": "광휘 신성 강타",
  "Raise Hood": "두건 올리기",
  "Raise Zombie": "좀비 일으키기",
  "Read": "읽기",
  "Reassert Control": "제어 재확립",
  "Recall Chest": "상자 회수",
  "Recall Object": "물체 회수",
  "Recharge Rage on Initiative": "선제권에 분노 재충전",
  "Recharge on Initiative": "선제권에 재충전",
  "Recharge with Rage": "분노로 재충전",
  "Recharge with Spell Slot": "주문 슬롯으로 재충전",
  "Recover": "회복",
  "Recover Ball Bearings": "쇠구슬 회수",
  "Recover Spell Slots": "주문 슬롯 회복",
  "Red Corundum": "레드 커런덤",
  "Redirect": "방향 전환",
  "Reduce": "축소",
  "Reduce Damage": "피해 감소",
  "Reduce Unwilling Movement": "비자발적 이동 감소",
  "Reflect Enchantment": "환혹 반사",
  "Reflect Spell": "주문 반사",
  "Regain Pact Spell Slots": "조약 주문 슬롯 회복",
  "Regain Sorcery Points": "소서리 점수 회복",
  "Regain Spell Slot": "주문 슬롯 회복",
  "Regain Use": "사용 횟수 회복",
  "Regain Wild Shape": "야생 변신 회복",
  "Regeneration": "재생",
  "Regurgitate: Save": "토해내기: 내성",
  "Reheat": "재가열",
  "Release Creature": "크리처 방출",
  "Relentlessly Endure": "끈질긴 인내",
  "Remove Poison": "독 제거",
  "Remove Stopper": "마개 제거",
  "Repair Rope": "밧줄 수리",
  "Reset Progress": "진행 초기화",
  "Resist Enchantment": "환혹 저항",
  "Resistances": "저항",
  "Restore Innate Sorcery": "타고난 마법 회복",
  "Restore Slots": "슬롯 회복",
  "Restore Sorcery Points": "소서리 점수 회복",
  "Restore Use": "사용 횟수 회복",
  "Retaliate": "반격",
  "Retributive Strike": "응징의 일격",
  "Retributive Strike: Save": "응징의 일격: 내성",
  "Return from Host": "숙주에서 귀환",
  "Revert or Recall Goat of Traveling": "여행의 염소 되돌리기 또는 회수",
  "Revive": "소생",
  "Revive: Days": "소생: 일수",
  "Ring of Resistance": "저항의 반지",
  "Roll d6": "d6 굴림",
  "Roll d8": "d8 굴림",
  "Roll for Explosion Chance": "폭발 확률 굴림",
  "Rope (Coiled)": "밧줄 (감긴 상태)",
  "STR Score -1d4": "근력치 -1d4",
  "Sack": "자루",
  "Save": "내성",
  "Save (free casting)": "내성 (무료 시전)",
  "Save on Target": "대상에게 내성",
  "Save while Restrained": "포박 중 내성",
  "Sculpt Element": "원소 조형",
  "Seal or Pry Open": "봉인 또는 비집어 열기",
  "Searing Light": "작열하는 빛",
  "Second Command Word": "두 번째 명령어",
  "Second Roar: Save": "두 번째 포효: 내성",
  "Second Save": "두 번째 내성",
  "Second+ Use": "두 번째 이후 사용",
  "Secondhand and Body Part": "간접 및 신체 부위",
  "Secondhand and Garment": "간접 및 의복",
  "Secondhand and Picture": "간접 및 사진",
  "Seeking Spell": "추적 주문",
  "Select Dragon Type": "드래곤 종류 선택",
  "Self Damage": "자기 피해",
  "Send Alone or Recall": "단독 보내기 또는 회수",
  "Sense Thoughts": "생각 감지",
  "Set Trap": "함정 설치",
  "Shadow Rises": "섀도우 일어남",
  "Shape-Shift: Succubus": "형태 변환: 서큐버스",
  "Shard Explosion": "파편 폭발",
  "Share Acid Resistance": "산성 저항 공유",
  "Share Cold Resistance": "냉기 저항 공유",
  "Share Fire Resistance": "화염 저항 공유",
  "Share Lightning Resistance": "번개 저항 공유",
  "Share Poison Resistance": "독성 저항 공유",
  "Shield, +1, +2, or +3": "방패, +1, +2, 또는 +3",
  "Shooting Stars": "별똥별",
  "Slaying Save": "학살 내성",
  "Sleep": "수면",
  "Sleight of Hand": "손재주",
  "Slow": "둔화",
  "Small Horizontal Portal": "소형 수평 차원문",
  "Small Vertical Portal": "소형 수직 차원문",
  "Smite": "강타",
  "Snare Missile": "투사체 포획",
  "Speak with Animals": "동물과 대화",
  "Speak with Plants": "식물과 대화",
  "Spectral Trees and Vines": "유령 나무와 덩굴",
  "Spell Absorption": "주문 흡수",
  "Spell Glyph": "주문 결계 문양",
  "Spellcasting Attack": "주문시전 공격",
  "Sphere or Globe": "구체 또는 구",
  "Spill Ball Bearings": "쇠구슬 쏟기",
  "Spirit Rises": "영혼 일어남",
  "Splash": "튀기기",
  "Split": "분열",
  "Sprinkle on Elemental": "정령에게 뿌리기",
  "Sprinkle over Water": "물 위에 뿌리기",
  "Square Panels": "사각 패널",
  "Stabilize": "안정",
  "Staggering Blow": "비틀거리게 하는 강타",
  "Staked to the Heart": "심장에 말뚝 박힘",
  "Stanch Wound Check": "지혈 판정",
  "Start of Turn Damage": "턴 시작 피해",
  "Start of Turn Effects": "턴 시작 효과",
  "Start of Turn Save": "턴 시작 내성",
  "Steady Aim": "조준 안정",
  "Step of the Wind": "바람의 발걸음",
  "Stonecunning": "암석 감지",
  "Store Spell by Level": "레벨별 주문 저장",
  "Storm's Thunder": "폭풍의 천둥",
  "Stream of Gems (88-92)": "보석의 물줄기 (88-92)",
  "Stroke of Luck": "행운의 일격",
  "Stunning": "기절시키기",
  "Subtle Spell": "교묘한 주문",
  "Succeed": "성공",
  "Successive Failed Save Damage": "연속 내성 실패 피해",
  "Summon Elemental": "정령 소환",
  "Summon Flying Steed": "비행 탈것 소환",
  "Summon Flying Steed (free casting)": "비행 탈것 소환 (무료 시전)",
  "Summon Steed": "탈것 소환",
  "Summon Steed (free casting)": "탈것 소환 (무료 시전)",
  "Summon Warriors": "전사 소환",
  "Summon with Spell Slot": "주문 슬롯으로 소환",
  "Summon with Wild Shape": "야생 변신으로 소환",
  "Sundering Blow": "분쇄하는 강타",
  "Swallowed": "삼켜짐",
  "Sway Rats": "쥐 조종",
  "Swear Oath": "맹세하기",
  "Sword of Life Stealing": "생명 강탈의 검",
  "Sword of Sharpness": "예리함의 검",
  "Sword of Wounding": "상처의 검",
  "Sword of Wounding Save": "상처의 검 내성",
  "Sympathy Save": "공감 내성",
  "Target: HP Loss": "대상: HP 상실",
  "Taxing Cast": "소모적 시전",
  "Teleport": "순간이동",
  "Teleport and Attack": "순간이동 후 공격",
  "Teleport to Sanctuary": "성소로 순간이동",
  "Temp. Healing": "임시 치유",
  "Temporary Healing": "임시 치유",
  "Temporary Health": "임시 생명력",
  "Temporary Hit Points": "임시 HP",
  "Terrify": "공포에 빠뜨리기",
  "Thieves' Tools": "도둑 도구",
  "Third Command Word": "세 번째 명령어",
  "Third Roar: Save": "세 번째 포효: 내성",
  "Throw": "투척",
  "Throw Acid": "산성 던지기",
  "Throw Bands": "결박대 던지기",
  "Throw Bead": "구슬 던지기",
  "Throw Held Globe": "들고 있는 구체 던지기",
  "Thunder": "천둥",
  "Thunder & Lightning": "천둥과 번개",
  "Thunderclap": "천둥소리",
  "Tie Knot": "매듭 묶기",
  "Topple": "쓰러뜨리기",
  "Total Cover": "완전 엄폐",
  "Touch Bead": "구슬 만지기",
  "Transfer Soul": "영혼 전이",
  "Transform Into Bat": "박쥐로 변신",
  "Transform into Snake": "뱀으로 변신",
  "Transform to Cloud": "구름으로 변신",
  "Transmuted Spell": "변환된 주문",
  "Transport": "전송",
  "Transport to Demiplane": "데미플레인으로 전송",
  "Traversal Save": "통과 내성",
  "Tree Form": "나무 형태",
  "Trigger (1-4)": "발동 (1-4)",
  "Trigger (11-16)": "발동 (11-16)",
  "Trigger (17-20)": "발동 (17-20)",
  "Trigger (5-10)": "발동 (5-10)",
  "Trigger Explosion": "폭발 발동",
  "Trip": "걸어 넘어뜨리기",
  "Troll": "트롤",
  "Troll Limb": "트롤 사지",
  "Turn 2: Acid Rain": "2턴: 산성비",
  "Turn 3: Lightning": "3턴: 번개",
  "Turn 4: Hailstones": "4턴: 우박",
  "Turn 5+: Gusts and Rain": "5턴 이후: 돌풍과 비",
  "Turn End Damage Increase": "턴 종료 피해 증가",
  "Turn Undead": "언데드 퇴치",
  "Twinned Spell": "쌍둥이 주문",
  "Ultimate End": "궁극의 종말",
  "Uncanny Dodge": "기묘한 회피",
  "Uncanny Metabolism": "기묘한 신진대사",
  "Unfold": "펼치기",
  "Unfold Portable Hole": "휴대용 구멍 펼치기",
  "Unholy Creature Damage": "부정한 크리처 피해",
  "Unholy Creature Damage (free casting)": "부정한 크리처 피해 (무료 시전)",
  "Unknown Spell Check": "미지의 주문 판정",
  "Unwilling Save": "비자발적 내성",
  "Use": "사용",
  "Use (free casting)": "사용 (무료 시전)",
  "Use (free casting) (free casting)": "사용 (무료 시전) (무료 시전)",
  "Use (free casting) (free casting) (free casting)": "사용 (무료 시전) (무료 시전) (무료 시전)",
  "Use First Lion": "첫 번째 사자 사용",
  "Use Poison": "독 사용",
  "Use Second Lion": "두 번째 사자 사용",
  "Use an Object": "물체 사용",
  "Utilize": "활용",
  "Utilize (Scale by Spell Level)": "활용 (주문 레벨에 따라 증가)",
  "Vampire Spawn Rises": "뱀파이어 스폰 일어남",
  "Veil": "장막",
  "Vicious Weapon": "잔혹한 무기",
  "Violet Save (Wis)": "보라색 내성 (지혜)",
  "Vorpal Sword": "보팔 소드",
  "Wand of the War Mage, +1, +2, or +3": "전쟁 마법사의 마법봉, +1, +2, 또는 +3",
  "Wave of Terror": "공포의 물결",
  "Weapon of Warning": "경고의 무기",
  "Weapon, +1, +2, or +3": "무기, +1, +2, 또는 +3",
  "While Concentrating": "집중하는 동안",
  "Whisper": "속삭임",
  "Whistle": "휘파람",
  "Wisp: Healing": "도깨비불: 치유",
  "Withdraw": "물러나기",
  "Wrap Chain Check": "사슬 감기 판정",
  "Write Name": "이름 쓰기",
  "Years Older": "나이 증가",
  "Yellow Diamond": "옐로 다이아몬드",
  "Zombie Rises": "좀비 일어남"
};

/** Babele 필드 컨버터: system.activities 객체를 받아 각 activity.name을 사전으로 치환. */
export function activityNames(activities) {
  if (!activities || typeof activities !== "object") return activities;
  for (const a of Object.values(activities)) {
    if (a && typeof a.name === "string" && ACTIVITY_NAME_MAP[a.name]) a.name = ACTIVITY_NAME_MAP[a.name];
  }
  return activities;
}
